"""Constants for the Candy integration."""

DOMAIN = "candy"
PLATFORMS = ["sensor", "button", "select"]

DATA_KEY_COORDINATOR = "coordinator"
DATA_KEY_CLIENT = "client"
DATA_KEY_LAST_PROGRAM = "last_program"

CONF_INTEGRATION_TITLE = "Candy"
CONF_KEY_USE_ENCRYPTION = "use_encryption"

SERVICE_SEND_COMMAND = "send_command"
SERVICE_SEND_RAW_COMMAND = "send_raw_command"
SERVICE_SEND_PLAINTEXT_COMMAND = "send_plaintext_command"
SERVICE_DECRYPT_DATA = "decrypt_data"
SERVICE_WM_START = "washing_machine_start"
SERVICE_WM_STOP = "washing_machine_stop"
SERVICE_WM_PAUSE = "washing_machine_pause"
SERVICE_WM_RESUME = "washing_machine_resume"
SERVICE_TD_START = "tumble_dryer_start"
SERVICE_TD_STOP = "tumble_dryer_stop"
SERVICE_TD_PAUSE = "tumble_dryer_pause"
SERVICE_TD_RESUME = "tumble_dryer_resume"
ATTR_PARAMS = "params"
ATTR_DATA = "data"
ATTR_PLAINTEXT = "plaintext"
ATTR_PROGRAM = "program"
ATTR_TEMP = "temp"
ATTR_SPIN_TARGET = "spin_target"
ATTR_SPIN_DEFAULT = "spin_default"
ATTR_SOIL_LEVEL = "soil_level"
ATTR_STEAM = "steam"
ATTR_DRY_LEVEL = "dry_level"
ATTR_DRY_LEVEL_TARGET = "dry_level_target"
ATTR_RAPID = "rapid"

UNIQUE_ID_WASHING_MACHINE = "{0}-washing_machine"
UNIQUE_ID_WASH_CYCLE_STATUS = "{0}-wash_cycle_status"
UNIQUE_ID_WASH_REMAINING_TIME = "{0}-wash_remaining_time"
UNIQUE_ID_WASH_START_BUTTON = "{0}-wash_start_button"
UNIQUE_ID_WASH_PAUSE_BUTTON = "{0}-wash_pause_button"
UNIQUE_ID_WASH_RESUME_BUTTON = "{0}-wash_resume_button"
UNIQUE_ID_WASH_STOP_BUTTON = "{0}-wash_stop_button"
UNIQUE_ID_TUMBLE_DRYER = "{0}-tumble_dryer"
UNIQUE_ID_TUMBLE_CYCLE_STATUS = "{0}-tumble_cycle_status"
UNIQUE_ID_TUMBLE_REMAINING_TIME = "{0}-tumble_remaining_time"
UNIQUE_ID_TUMBLE_PAUSE_BUTTON = "{0}-tumble_pause_button"
UNIQUE_ID_TUMBLE_RESUME_BUTTON = "{0}-tumble_resume_button"
UNIQUE_ID_TUMBLE_STOP_BUTTON = "{0}-tumble_stop_button"

UNIQUE_ID_OVEN = "{0}-oven"
UNIQUE_ID_OVEN_TEMP = "{0}-oven-temp"
UNIQUE_ID_OVEN_PAUSE_BUTTON = "{0}-oven_pause_button"
UNIQUE_ID_OVEN_RESUME_BUTTON = "{0}-oven_resume_button"
UNIQUE_ID_DISHWASHER = "{0}-dishwasher"
UNIQUE_ID_DISHWASHER_REMAINING_TIME = "{0}-dishwasher_remaining_time"
UNIQUE_ID_DISHWASHER_PAUSE_BUTTON = "{0}-dishwasher_pause_button"
UNIQUE_ID_DISHWASHER_RESUME_BUTTON = "{0}-dishwasher_resume_button"

DEVICE_NAME_WASHING_MACHINE = "Washing machine"
DEVICE_NAME_TUMBLE_DRYER = "Tumble dryer"
DEVICE_NAME_OVEN = "Oven"
DEVICE_NAME_DISHWASHER = "Dishwasher"

SUGGESTED_AREA_BATHROOM = "Bathroom"
SUGGESTED_AREA_KITCHEN = "Kitchen"
