"""Constants for the Candy integration."""

DOMAIN = "candy"
PLATFORMS = ["sensor", "binary_sensor", "button", "select", "number"]

DATA_KEY_COORDINATOR = "coordinator"
DATA_KEY_CLIENT = "client"
DATA_KEY_LAST_PROGRAM = "last_program"
DATA_KEY_WM_TEMP = "wm_temp"
DATA_KEY_WM_SPIN = "wm_spin"
DATA_KEY_WM_SOIL = "wm_soil"
DATA_KEY_WM_STEAM = "wm_steam"
DATA_KEY_TD_DRY_LEVEL = "td_dry_level"
DATA_KEY_TD_TIME = "td_time"
DATA_KEY_WM_CATEGORY = "wm_category"
DATA_KEY_TD_CATEGORY = "td_category"

# Dispatcher signals
SIGNAL_WM_PROGRAM_CHANGED = "candy_{}_wm_program_changed"
SIGNAL_WM_CATEGORY_CHANGED = "candy_{}_wm_category_changed"
SIGNAL_TD_CATEGORY_CHANGED = "candy_{}_td_category_changed"
SIGNAL_TD_PROGRAM_CHANGED = "candy_{}_td_program_changed"

CONF_INTEGRATION_TITLE = "Candy"
CONF_KEY_USE_ENCRYPTION = "use_encryption"

SERVICE_SEND_COMMAND = "send_command"
SERVICE_SEND_RAW_COMMAND = "send_raw_command"
SERVICE_SEND_PLAINTEXT_COMMAND = "send_plaintext_command"
SERVICE_DECRYPT_DATA = "decrypt_data"
SERVICE_WM_START = "washing_machine_start"
SERVICE_WM_STOP = "washing_machine_stop"
SERVICE_WM_PAUSE = "washing_machine_pause"
SERVICE_WM_RESUME = "washing_machine_resume"
SERVICE_TD_START = "tumble_dryer_start"
SERVICE_TD_STOP = "tumble_dryer_stop"
SERVICE_TD_PAUSE = "tumble_dryer_pause"
SERVICE_TD_RESUME = "tumble_dryer_resume"
ATTR_PARAMS = "params"
ATTR_DATA = "data"
ATTR_PLAINTEXT = "plaintext"
ATTR_PROGRAM = "program"
ATTR_TEMP = "temp"
ATTR_SPIN_TARGET = "spin_target"
ATTR_SPIN_DEFAULT = "spin_default"
ATTR_SOIL_LEVEL = "soil_level"
ATTR_STEAM = "steam"
ATTR_DRY_LEVEL = "dry_level"
ATTR_DRY_LEVEL_TARGET = "dry_level_target"
ATTR_RAPID = "rapid"

UNIQUE_ID_WASHING_MACHINE = "{0}-washing_machine"
UNIQUE_ID_WASH_CYCLE_STATUS = "{0}-wash_cycle_status"
UNIQUE_ID_WASH_REMAINING_TIME = "{0}-wash_remaining_time"
UNIQUE_ID_WASH_START_BUTTON = "{0}-wash_start_button"
UNIQUE_ID_WASH_PAUSE_BUTTON = "{0}-wash_pause_button"
UNIQUE_ID_WASH_RESUME_BUTTON = "{0}-wash_resume_button"
UNIQUE_ID_WASH_STOP_BUTTON = "{0}-wash_stop_button"
UNIQUE_ID_TUMBLE_DRYER = "{0}-tumble_dryer"
UNIQUE_ID_TUMBLE_CYCLE_STATUS = "{0}-tumble_cycle_status"
UNIQUE_ID_TUMBLE_REMAINING_TIME = "{0}-tumble_remaining_time"
UNIQUE_ID_TUMBLE_START_BUTTON = "{0}-tumble_start_button"
UNIQUE_ID_TUMBLE_PAUSE_BUTTON = "{0}-tumble_pause_button"
UNIQUE_ID_TUMBLE_RESUME_BUTTON = "{0}-tumble_resume_button"
UNIQUE_ID_TUMBLE_STOP_BUTTON = "{0}-tumble_stop_button"

UNIQUE_ID_WM_TEMP = "{0}-wm_temperature"
UNIQUE_ID_WM_SPIN = "{0}-wm_spin_speed"
UNIQUE_ID_WM_SOIL = "{0}-wm_soil_level"
UNIQUE_ID_WM_STEAM = "{0}-wm_steam"
UNIQUE_ID_TD_TIME_NUMBER = "{0}-td_time_number"
UNIQUE_ID_TD_DRY_LEVEL_SELECT = "{0}-td_dry_level_select"

# Read-only sensor unique IDs
UNIQUE_ID_WM_PROGRAM_SENSOR = "{0}-wm_program_sensor"
UNIQUE_ID_WM_TEMP_SENSOR = "{0}-wm_temp_sensor"
UNIQUE_ID_WM_SPIN_SENSOR = "{0}-wm_spin_sensor"
UNIQUE_ID_WM_SOIL_SENSOR = "{0}-wm_soil_sensor"
UNIQUE_ID_WM_ERROR = "{0}-wm_error"
UNIQUE_ID_WM_DELAY_START = "{0}-wm_delay_start"
UNIQUE_ID_TD_DRY_LEVEL = "{0}-td_dry_level_sensor"
UNIQUE_ID_TD_ERROR = "{0}-td_error"
UNIQUE_ID_TD_DELAY_START = "{0}-td_delay_start"
UNIQUE_ID_TD_DOOR = "{0}-td_door"
UNIQUE_ID_TD_FILTER = "{0}-td_filter"
UNIQUE_ID_TD_WATER_TANK = "{0}-td_water_tank"

UNIQUE_ID_OVEN = "{0}-oven"
UNIQUE_ID_OVEN_TEMP = "{0}-oven-temp"
UNIQUE_ID_OVEN_PAUSE_BUTTON = "{0}-oven_pause_button"
UNIQUE_ID_OVEN_RESUME_BUTTON = "{0}-oven_resume_button"
UNIQUE_ID_DISHWASHER = "{0}-dishwasher"
UNIQUE_ID_DISHWASHER_REMAINING_TIME = "{0}-dishwasher_remaining_time"
UNIQUE_ID_DISHWASHER_PAUSE_BUTTON = "{0}-dishwasher_pause_button"
UNIQUE_ID_DISHWASHER_RESUME_BUTTON = "{0}-dishwasher_resume_button"

DEVICE_NAME_WASHING_MACHINE = "Washing machine"
DEVICE_NAME_TUMBLE_DRYER = "Tumble dryer"
DEVICE_NAME_OVEN = "Oven"
DEVICE_NAME_DISHWASHER = "Dishwasher"

SUGGESTED_AREA_BATHROOM = "Bathroom"
SUGGESTED_AREA_KITCHEN = "Kitchen"

DATA_KEY_PLATFORMS_LOADED = "platforms_loaded"
DATA_KEY_SETUP_RETRY_UNSUB = "setup_retry_unsub"
