"""Program definitions captured from Simply-Fi backend."""
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class WashProgram:
    name: str
    program: int
    temp: Optional[int] = None
    spin_target: Optional[int] = None
    spin_default: Optional[int] = None
    soil_level: Optional[int] = None
    steam: int = 0
    opt_mask: int = 0


WASHING_MACHINE_PROGRAMS: list[WashProgram] = [
    # === Base cycles (selector_position 1–19 from appliance backend) ===
    WashProgram("Perfect 20", program=1),
    WashProgram("Coloured 40", program=2),
    WashProgram("Hygiene 60", program=3, spin_target=15, spin_default=10),
    WashProgram("Perfect Rapid 59'", program=4),
    WashProgram("Rapid 14 min", program=5),
    WashProgram("Rapid 30 min", program=5, soil_level=2),
    WashProgram("Rapid 44 min", program=5, soil_level=3),
    WashProgram("Handwash & Silk", program=6, temp=30, spin_target=8, spin_default=8),
    WashProgram("Wool", program=7, temp=40, spin_target=8, spin_default=8),
    WashProgram("Rinse", program=8),
    WashProgram("Drain & Spin 1500", program=9, spin_target=15, spin_default=10),
    WashProgram("Drain & Spin 700", program=9, spin_target=7, spin_default=10),
    WashProgram("Delicates", program=10, temp=40, spin_target=4, spin_default=4, steam=1),
    WashProgram("Synthetics", program=11, temp=40, soil_level=3, spin_target=10, spin_default=10, steam=1),
    WashProgram("Cottons", program=12, temp=40, soil_level=3, spin_target=15, spin_default=15, steam=2),
    WashProgram("Whites", program=12, temp=90, soil_level=3, spin_target=14, spin_default=14, steam=2),
    WashProgram("Resistant Cottons", program=13, temp=60, soil_level=3, spin_target=15, spin_default=10, steam=2),
    WashProgram("Mixed + Easy Iron", program=14, temp=30, soil_level=1, spin_target=10, spin_default=10),
    # Smart Fi Plus: default_temperature=60 per API (maximum=90); spin lvl 4
    WashProgram("Smart Fi Plus", program=15, temp=60, soil_level=1, spin_target=4, spin_default=4),
    # Silk: default+maximum spin=800 RPM (lvl 8) per API
    WashProgram("Silk", program=18, temp=30, spin_target=8, spin_default=8),
    WashProgram("Daily 59 min", program=19, temp=60, spin_target=15, spin_default=10),
    # === Downloadable programs from Simply-Fi cloud (wm_wd_programs.json) ===
    # Each runs on the parent base cycle (`program` below) with these defaults.
    # — Baby —
    WashProgram("Baby Sanitizer", program=1, temp=60, soil_level=3, spin_target=15, spin_default=15, opt_mask=2),
    WashProgram("Cuddly Toys", program=11, temp=40, spin_target=4, spin_default=4),
    WashProgram("Playsuits", program=2, temp=40, soil_level=2, spin_target=10, spin_default=10, opt_mask=16),
    # — Business —
    WashProgram("Men's Trousers", program=9, temp=40, spin_target=10, spin_default=10),
    WashProgram("Shirts", program=9, temp=30, spin_target=10, spin_default=10, opt_mask=16),
    # — Home Care —
    WashProgram("Bathrobe", program=9, temp=40, spin_target=10, spin_default=10, opt_mask=16),
    WashProgram("Bed Linen", program=1, temp=40, soil_level=2, spin_target=15, spin_default=15, opt_mask=16),
    WashProgram("Bed Linen Coloured", program=10, temp=40, soil_level=2, spin_target=10, spin_default=10),
    WashProgram("Curtains", program=4, temp=30, spin_target=4, spin_default=4, opt_mask=1),
    WashProgram("Curtains Coloured", program=11, temp=30, spin_target=4, spin_default=4),
    WashProgram("Delicate Tablecloths", program=2, temp=30, soil_level=1, spin_target=8, spin_default=8),
    WashProgram("Denim Jeans", program=9, temp=40, spin_target=10, spin_default=10),
    WashProgram("Duvet & Quilts", program=11, temp=30, spin_target=4, spin_default=4),
    WashProgram("Mats", program=10, temp=40, soil_level=2, spin_target=8, spin_default=8, opt_mask=1),
    WashProgram("Swimsuits & Bikinis", program=7, temp=30, spin_target=9, spin_default=9),
    WashProgram("Tablecloths", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Tablecloths Coloured", program=10, temp=40, soil_level=3, spin_target=10, spin_default=10),
    # — Energy Saver / Rapid —
    WashProgram("Rapid Delicates 30 min", program=6, temp=30, soil_level=2, spin_target=10, spin_default=10),
    WashProgram("Refresh 14 min", program=5, temp=30, soil_level=1, spin_target=10, spin_default=10),
    WashProgram("Time Saver Cotton", program=10, temp=40, soil_level=1, spin_target=10, spin_default=10),
    WashProgram("Time Saver Mixed", program=2, temp=40, soil_level=1, spin_target=10, spin_default=10),
    # — Stains —
    WashProgram("Bleaching", program=8, spin_target=10, spin_default=10),
    WashProgram("Blood Stains", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Chocolate Stains", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Colored Anti-Stain", program=1, temp=40, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Fruit Stains", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Perfect White", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Stain Remover", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Wine Stains", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    # — Health & Wellness —
    WashProgram("Anti-Mites", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Anti-Odor", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10, opt_mask=2),
    WashProgram("Delicate Antiallergy", program=11, temp=40, spin_target=4, spin_default=4),
    WashProgram("Masks Sanification", program=1, temp=60, soil_level=3, spin_target=10, spin_default=10),
    WashProgram("Masks Refresh", program=12, temp=40, soil_level=3, spin_target=10, spin_default=10),
    WashProgram("New Clothes", program=6, temp=20, soil_level=2, spin_target=10, spin_default=10),
    WashProgram("Pets", program=9, temp=40, spin_target=10, spin_default=10),
    # — Sports —
    WashProgram("Backpacks", program=11, temp=30, spin_target=4, spin_default=4),
    WashProgram("Diving Suits", program=11, spin_target=4, spin_default=4),
    WashProgram("Gym Fit", program=7, temp=30, spin_target=10, spin_default=10),
    WashProgram("Ski Suit", program=11, temp=30, spin_target=4, spin_default=4),
    WashProgram("Technical Fabrics", program=7, temp=30, spin_target=10, spin_default=10),
    WashProgram("Technical Jackets", program=11, temp=30, spin_target=4, spin_default=4),
    WashProgram("Trainers", program=11, temp=20, spin_target=4, spin_default=4),
    # — Delicate Fabrics —
    WashProgram("Cashmere", program=3, temp=20, spin_target=6, spin_default=6),
    WashProgram("Colored", program=10, temp=30, soil_level=2, spin_target=10, spin_default=10),
    WashProgram("Dark", program=2, temp=30, soil_level=2, spin_target=10, spin_default=10),
    WashProgram("Delicate Colored", program=2, temp=20, soil_level=1, spin_target=8, spin_default=8),
    WashProgram("Down Jackets", program=11, temp=30, spin_target=4, spin_default=4),
    WashProgram("Lingerie", program=7, temp=30, spin_target=8, spin_default=8),
    WashProgram("Silk (download)", program=3, temp=30, spin_target=8, spin_default=8),
]

WASHING_MACHINE_PROGRAMS_BY_NAME: dict[str, WashProgram] = {
    p.name: p for p in WASHING_MACHINE_PROGRAMS
}


@dataclass(frozen=True)
class TumbleDryerProgram:
    name: str
    program: int
    time: int = 0       # max_time_level / program_time_level → Time in START command
    opt_mask: int = 0   # mask1 → OptMsk in START command (base cycles)
    dry_level: int = 0  # program_drying_level → DryLev in START command (downloadable)
    selection: int = 0  # program_selection → Sel in START command (downloadable)
    rapid: int = 0      # rapid_level → Rapid in START command (downloadable)


TUMBLE_DRYER_PROGRAMS: list[TumbleDryerProgram] = [
    # === Base cycles (selector_position 1–15 from appliance backend) ===
    TumbleDryerProgram("Whites", program=1, time=20, opt_mask=20),
    TumbleDryerProgram("Eco", program=2, time=0, opt_mask=0),
    TumbleDryerProgram("Whites Plus", program=3, time=20, opt_mask=20),
    TumbleDryerProgram("Jeans", program=4, time=0, opt_mask=0),
    TumbleDryerProgram("Darks & Coloured", program=5, time=0, opt_mask=20),
    TumbleDryerProgram("Synthetics", program=6, time=13, opt_mask=20),
    TumbleDryerProgram("Shirts", program=7, time=0, opt_mask=20),
    TumbleDryerProgram("Woolmark", program=8),
    TumbleDryerProgram("Daily Perfect 59'", program=9),
    TumbleDryerProgram("Daily 45 min", program=10),
    TumbleDryerProgram("Saving 30 min", program=11),
    TumbleDryerProgram("Refresh", program=12),
    TumbleDryerProgram("Relax Creases", program=13),
    TumbleDryerProgram("Sport Plus", program=14),
    TumbleDryerProgram("Small Load", program=15),
    # === Downloadable programs from Simply-Fi cloud (td_wifi_download_program) ===
    # `program` = parent base cycle (PrNm), `selection`/`dry_level`/`rapid` are
    # downloadable-only parameters appended to the START command when non-zero.
    # — Home Care —
    TumbleDryerProgram("Bathrobe", program=22, selection=2, dry_level=4),
    TumbleDryerProgram("Bed Linen", program=22, selection=2, dry_level=3),
    TumbleDryerProgram("Denim Jeans", program=23, selection=9, dry_level=4),
    TumbleDryerProgram("Duvet", program=23, time=4),
    TumbleDryerProgram("Curtains", program=24, selection=8, dry_level=2),
    TumbleDryerProgram("Delicate Tablecloths", program=24, selection=8, dry_level=3),
    TumbleDryerProgram("Playsuits", program=24, selection=8, dry_level=3),
    TumbleDryerProgram("Cuddly Toys", program=25, selection=12, dry_level=4),
    TumbleDryerProgram("Tablecloths", program=27, selection=4, dry_level=4),
    TumbleDryerProgram("Anti-Mites", program=29, selection=12, dry_level=4),
    # — Special Care —
    TumbleDryerProgram("Baby", program=30, selection=4, dry_level=3),
    TumbleDryerProgram("Easy Iron Cotton", program=31, selection=3, dry_level=2),
    TumbleDryerProgram("Easy Iron Synthetics", program=31, selection=10, dry_level=2),
    TumbleDryerProgram("Gym Fit", program=32, selection=10, dry_level=2),
    TumbleDryerProgram("Swimsuits & Bikinis", program=32, selection=10),
    TumbleDryerProgram("Technical Fabrics", program=32, selection=10, dry_level=2),
    TumbleDryerProgram("Backpacks", program=33, time=7, selection=8),
    TumbleDryerProgram("Rapid 60 min Delicates", program=34, selection=8, rapid=2),
    TumbleDryerProgram("Lingerie", program=24, selection=8, dry_level=2),
    TumbleDryerProgram("Delicates Antiallergy", program=24, selection=8, dry_level=2),
    # Renamed from "Shirts (download)" to avoid confusion with base cycle "Shirts"
    TumbleDryerProgram("Shirts Delicate", program=24, selection=7, dry_level=3),
    # — Refresh / Special —
    TumbleDryerProgram("Air Refresh", program=35, selection=8, rapid=1),
    TumbleDryerProgram("Warm Embrace", program=35, selection=8, rapid=1),
    TumbleDryerProgram("Dehumidifier", program=35, selection=8, rapid=1),
    TumbleDryerProgram("Regenerates Waterproof", program=35, selection=8, rapid=1),
]

TUMBLE_DRYER_PROGRAMS_BY_NAME: dict[str, TumbleDryerProgram] = {
    p.name: p for p in TUMBLE_DRYER_PROGRAMS
}


WASHING_MACHINE_PROGRAM_DESCRIPTIONS_SQ: dict[str, str] = {
    "Perfect 20": "Larje në 20°C për rroba të përditshme me konsum të ulët.",
    "Coloured 40": "Për rroba me ngjyra në 40°C.",
    "Hygiene 60": "Program higjienizues në 60°C për pastrim më të thellë.",
    "Rapid 14 min": "Larje shumë e shpejtë për rroba pak të ndotura.",
    "Rapid 30 min": "Larje e shpejtë 30 minuta.",
    "Rapid 44 min": "Larje e shpejtë 44 minuta për ngarkesë të vogël/mesatare.",
    "Handwash & Silk": "Për rroba delikate dhe mëndafsh.",
    "Wool": "Program i butë për lesh.",
    "Rinse": "Vetëm shpëlarje.",
    "Drain & Spin 1500": "Shkarkim uji dhe shtrydhje e fortë.",
    "Drain & Spin 700": "Shkarkim uji dhe shtrydhje e lehtë.",
    "Delicates": "Për rroba delikate.",
    "Synthetics": "Për materiale sintetike.",
    "Cottons": "Për pambuk dhe rroba të përditshme.",
    "Whites": "Për rroba të bardha.",
    "Resistant Cottons": "Për pambuk më të fortë / më të ndotur.",
    "Mixed + Easy Iron": "Për rroba të përziera me hekurosje më të lehtë.",
    "Smart Fi Plus": "Program inteligjent i optimizuar nga cloud Simply-Fi.",
    "Silk": "Program i butë për mëndafsh dhe materiale shumë delikate.",
    "Daily 59 min": "Program ditor i shpejtë 59 minuta.",
    "Baby Sanitizer": "Program për rroba fëmijësh me higjienizim.",
    "Cuddly Toys": "Larje e butë për lodra të buta.",
    "Playsuits": "Për kostume dhe veshje loje fëmijësh.",
    "Men's Trousers": "Program për pantallona burri, redukton rrudhat.",
    "Shirts": "Program për këmisha, redukton rrudhat.",
    "Bathrobe": "Larje e butë për roba banjoje.",
    "Bed Linen": "Për çarçafë dhe mbulesa krevati.",
    "Bed Linen Coloured": "Për çarçafë dhe mbulesa krevati me ngjyra.",
    "Curtains": "Program i butë për perde.",
    "Curtains Coloured": "Program i butë për perde me ngjyra.",
    "Delicate Tablecloths": "Për mbulesë tryeze delikate.",
    "Denim Jeans": "Program për xhinse dhe materiale denim.",
    "Duvet & Quilts": "Për jorganë dhe batanije.",
    "Mats": "Për tepihë dhe shtroja.",
    "Swimsuits & Bikinis": "Larje e butë për kostume banje.",
    "Tablecloths": "Për mbulesë tryeze.",
    "Tablecloths Coloured": "Për mbulesë tryeze me ngjyra.",
    "Rapid Delicates 30 min": "Larje e shpejtë 30 min për delikate.",
    "Refresh 14 min": "Freskim i shpejtë 14 minuta.",
    "Time Saver Cotton": "Kursim kohe për pambuk.",
    "Time Saver Mixed": "Kursim kohe për rroba të përziera.",
    "Bleaching": "Program me zbardhues për rroba të bardha.",
    "Blood Stains": "Heqja e njollave të gjakut.",
    "Chocolate Stains": "Heqja e njollave të çokollatës.",
    "Colored Anti-Stain": "Anti-njolla për rroba me ngjyra.",
    "Fruit Stains": "Heqja e njollave të frutave.",
    "Perfect White": "Program për rroba të bardha pa njolla.",
    "Stain Remover": "Heqja e njollave të ndryshme.",
    "Wine Stains": "Heqja e njollave të verës.",
    "Anti-Mites": "Program anti-marimanga/alergjenë.",
    "Anti-Odor": "Program anti-erë për rroba me erë të keqe.",
    "Delicate Antiallergy": "Program anti-alergjik për rroba delikate.",
    "Masks Sanification": "Program për higjienizim maskash.",
    "Masks Refresh": "Freskim i maskave.",
    "New Clothes": "Program i butë për rroba të reja.",
    "Pets": "Larje e rrobave me qime kafshësh.",
    "Backpacks": "Larje e çantave të shpinës.",
    "Diving Suits": "Program i butë për kombinezone zhytjeje.",
    "Gym Fit": "Larje e veshjes sportive për palestër.",
    "Ski Suit": "Program i butë për kombinezone ski.",
    "Technical Fabrics": "Për materiale teknike sportive.",
    "Technical Jackets": "Për xhaketa teknike/impermeabile.",
    "Trainers": "Larje e atleteve dhe këpucëve sportive.",
    "Cashmere": "Program shumë i butë për kashmiri.",
    "Colored": "Për rroba me ngjyra delikate.",
    "Dark": "Për rroba të errëta, ruan ngjyrën.",
    "Delicate Colored": "Për rroba me ngjyra shumë delikate.",
    "Down Jackets": "Larje e xhaketave me pupla.",
    "Lingerie": "Program shumë i butë për të brendshme.",
    "Silk (download)": "Program i butë për mëndafsh nga cloud.",
}

TUMBLE_DRYER_PROGRAM_DESCRIPTIONS_SQ: dict[str, str] = {
    "Whites": "Tharje për rroba të bardha.",
    "Eco": "Tharje ekonomike me kursim energjie.",
    "Whites Plus": "Tharje e zgjeruar për rroba të bardha.",
    "Jeans": "Tharje për xhinse dhe materiale të trasha.",
    "Darks & Coloured": "Tharje për rroba të errëta dhe me ngjyra.",
    "Synthetics": "Tharje me nxehtësi mesatare për sintetikë.",
    "Shirts": "Tharje e butë për këmisha.",
    "Woolmark": "Tharje e kontrolluar për lesh.",
    "Daily Perfect 59'": "Program ditor rreth 59 minuta.",
    "Daily 45 min": "Program ditor 45 minuta.",
    "Saving 30 min": "Tharje e shpejtë me kursim 30 minuta.",
    "Refresh": "Freskim pa tharje të plotë.",
    "Relax Creases": "Relaksim rrudhash me avull.",
    "Sport Plus": "Për veshje sportive.",
    "Small Load": "Për ngarkesa të vogla.",
    "Bathrobe": "Për roba banjoje.",
    "Bed Linen": "Për çarçafë dhe mbulesa krevati.",
    "Denim Jeans": "Tharje e xhinse dhe denim.",
    "Duvet": "Për jorganë / batanije të trasha.",
    "Curtains": "Tharje e butë për perde.",
    "Delicate Tablecloths": "Tharje e butë për mbulesë tryeze delikate.",
    "Playsuits": "Tharje e butë për kostume loje.",
    "Cuddly Toys": "Tharje e butë për lodra të buta.",
    "Tablecloths": "Tharje e mbulesës së tryezës.",
    "Anti-Mites": "Program anti-marimanga.",
    "Baby": "Tharje e butë dhe e sigurt për veshjet e foshnjave.",
    "Easy Iron Cotton": "Tharje e pambukut për hekurosje të lehtë.",
    "Easy Iron Synthetics": "Tharje e sintetikëve për hekurosje të lehtë.",
    "Gym Fit": "Tharje e veshjes sportive.",
    "Swimsuits & Bikinis": "Tharje e butë për kostume banje.",
    "Technical Fabrics": "Tharje e materialeve teknike sportive.",
    "Backpacks": "Për çanta shpine dhe materiale të forta.",
    "Rapid 60 min Delicates": "Tharje e shpejtë 60 minuta për delikate.",
    "Lingerie": "Tharje shumë e butë për të brendshme.",
    "Delicates Antiallergy": "Tharje anti-alergjike për delikate.",
    "Shirts Delicate": "Tharje e butë për këmisha delikate.",
    "Air Refresh": "Qarkullim ajri për freskim.",
    "Warm Embrace": "Ngrohje e butë dhe freskim.",
    "Dehumidifier": "Program për ulje lagështie/freskim.",
    "Regenerates Waterproof": "Rigjenerimi i veshjes impermeabile.",
}


WASHING_MACHINE_PROGRAM_CATEGORY_SQ: dict[str, str] = {
    "Perfect 20": "Cycles",
    "Coloured 40": "Cycles",
    "Hygiene 60": "Cycles",
    "Perfect Rapid 59'": "Cycles",
    "Rapid 14 min": "Cycles",
    "Rapid 30 min": "Cycles",
    "Rapid 44 min": "Cycles",
    "Handwash & Silk": "Cycles",
    "Wool": "Cycles",
    "Rinse": "Cycles",
    "Drain & Spin 1500": "Cycles",
    "Drain & Spin 700": "Cycles",
    "Delicates": "Cycles",
    "Synthetics": "Cycles",
    "Cottons": "Cycles",
    "Whites": "Cycles",
    "Resistant Cottons": "Cycles",
    "Mixed + Easy Iron": "Cycles",
    "Smart Fi Plus": "Cycles",
    "Silk": "Cycles",
    "Daily 59 min": "Cycles",
    "Baby Sanitizer": "Baby Care",
    "Cuddly Toys": "Baby Care",
    "Playsuits": "Baby Care",
    "Anti-Mites": "Health & Hygiene",
    "Anti-Odor": "Health & Hygiene",
    "Delicate Antiallergy": "Health & Hygiene",
    "New Clothes": "Health & Hygiene",
    "Pets": "Health & Hygiene",
    "Masks Refresh": "Health & Hygiene",
    "Masks Sanification": "Health & Hygiene",
    "Bathrobe": "Home Care",
    "Bed Linen": "Home Care",
    "Bed Linen Coloured": "Home Care",
    "Curtains": "Home Care",
    "Curtains Coloured": "Home Care",
    "Denim Jeans": "Home Care",
    "Duvet & Quilts": "Home Care",
    "Mats": "Home Care",
    "Swimsuits & Bikinis": "Home Care",
    "Tablecloths": "Home Care",
    "Tablecloths Coloured": "Home Care",
    "Delicate Tablecloths": "Home Care",
    "Cashmere": "Special Care",
    "Colored": "Special Care",
    "Dark": "Special Care",
    "Delicate Colored": "Special Care",
    "Down Jackets": "Special Care",
    "Lingerie": "Special Care",
    "Silk (download)": "Special Care",
    "Backpacks": "Sport & Leisure",
    "Diving Suits": "Sport & Leisure",
    "Gym Fit": "Sport & Leisure",
    "Ski Suit": "Sport & Leisure",
    "Technical Fabrics": "Sport & Leisure",
    "Technical Jackets": "Sport & Leisure",
    "Trainers": "Sport & Leisure",
    "Bleaching": "Stains Proof",
    "Blood Stains": "Stains Proof",
    "Chocolate Stains": "Stains Proof",
    "Colored Anti-Stain": "Stains Proof",
    "Fruit Stains": "Stains Proof",
    "Perfect White": "Stains Proof",
    "Stain Remover": "Stains Proof",
    "Wine Stains": "Stains Proof",
    "Rapid Delicates 30 min": "Time & Energy Saver",
    "Refresh 14 min": "Time & Energy Saver",
    "Time Saver Cotton": "Time & Energy Saver",
    "Time Saver Mixed": "Time & Energy Saver",
    "Shirts": "Work",
    "Men's Trousers": "Work",
}

TUMBLE_DRYER_PROGRAM_CATEGORY_SQ: dict[str, str] = {
    "Whites": "Cycles",
    "Eco": "Cycles",
    "Whites Plus": "Cycles",
    "Jeans": "Cycles",
    "Darks & Coloured": "Cycles",
    "Synthetics": "Cycles",
    "Shirts": "Cycles",
    "Woolmark": "Cycles",
    "Daily Perfect 59'": "Cycles",
    "Daily 45 min": "Cycles",
    "Saving 30 min": "Cycles",
    "Refresh": "Cycles",
    "Relax Creases": "Cycles",
    "Sport Plus": "Cycles",
    "Small Load": "Cycles",
    "Baby": "Baby Care",
    "Cuddly Toys": "Baby Care",
    "Delicates Antiallergy": "Health & Hygiene",
    "Air Refresh": "Health & Hygiene",
    "Warm Embrace": "Health & Hygiene",
    "Dehumidifier": "Health & Hygiene",
    "Regenerates Waterproof": "Special Care",
    "Anti-Mites": "Health & Hygiene",
    "Bathrobe": "Home Care",
    "Bed Linen": "Home Care",
    "Curtains": "Home Care",
    "Denim Jeans": "Home Care",
    "Duvet": "Home Care",
    "Playsuits": "Home Care",
    "Tablecloths": "Home Care",
    "Delicate Tablecloths": "Home Care",
    "Woolmark": "Special Care",
    "Lingerie": "Special Care",
    "Easy Iron Cotton": "Special Care",
    "Easy Iron Synthetics": "Special Care",
    "Shirts Delicate": "Special Care",
    "Swimsuits & Bikinis": "Special Care",
    "Technical Fabrics": "Sport & Leisure",
    "Gym Fit": "Sport & Leisure",
    "Backpacks": "Sport & Leisure",
    "Rapid 60 min Delicates": "Time & Energy Saver",
    "Daily 45 min": "Time & Energy Saver",
    "Daily Perfect 59'": "Time & Energy Saver",
    "Saving 30 min": "Time & Energy Saver",
}


WASHING_MACHINE_PROGRAM_META_SQ: dict[str, dict[str, str]] = {
    "Perfect 20": {"category": "1. Cycles", "profile": "20°C / 1000 RPM"},
    "Coloured 40": {"category": "1. Cycles", "profile": "40°C / 1000 RPM"},
    "Hygiene 60": {"category": "1. Cycles", "profile": "40-60°C / 1000 RPM"},
    "Perfect Rapid 59'": {"category": "1. Cycles", "profile": "40°C / 1000 RPM"},
    "Rapid 14 min": {"category": "1. Cycles", "profile": "30°C / 800 RPM"},
    "Rapid 30 min": {"category": "1. Cycles", "profile": "30°C / 800 RPM"},
    "Rapid 44 min": {"category": "1. Cycles", "profile": "40°C / 1000 RPM"},
    "Handwash & Silk": {"category": "1. Cycles", "profile": "30°C / 400 RPM"},
    "Wool": {"category": "1. Cycles", "profile": "40°C / 800 RPM"},
    "Rinse": {"category": "1. Cycles", "profile": "0°C / 1000 RPM"},
    "Drain & Spin 1500": {"category": "1. Cycles", "profile": "0°C / 1400-1500 RPM"},
    "Drain & Spin 700": {"category": "1. Cycles", "profile": "0°C / 700 RPM"},
    "Delicates": {"category": "1. Cycles", "profile": "40°C / 800 RPM"},
    "Synthetics": {"category": "1. Cycles", "profile": "40°C / 1000 RPM"},
    "Cottons": {"category": "1. Cycles", "profile": "60°C / 1400 RPM"},
    "Whites": {"category": "1. Cycles", "profile": "90°C / 1400 RPM"},
    "Resistant Cottons": {"category": "1. Cycles", "profile": "60°C / 1400 RPM"},
    "Mixed + Easy Iron": {"category": "1. Cycles", "profile": "30°C / 1000 RPM"},
    "Smart Fi Plus": {"category": "1. Cycles", "profile": "60°C / 400 RPM"},
    "Silk": {"category": "1. Cycles", "profile": "30°C / 800 RPM"},
    "Daily 59 min": {"category": "1. Cycles", "profile": "60°C / 1000 RPM"},
    "Baby Sanitizer": {"category": "2. Baby Care", "profile": "60°C / 1000 RPM"},
    "Cuddly Toys": {"category": "2. Baby Care", "profile": "30-40°C / 400 RPM"},
    "Playsuits": {"category": "2. Baby Care", "profile": "40°C / 800 RPM"},
    "Anti-Mites": {"category": "3. Health & Hygiene", "profile": "60°C / 1000 RPM"},
    "Anti-Odor": {"category": "3. Health & Hygiene", "profile": "40-60°C / 1000 RPM"},
    "Delicate Antiallergy": {"category": "3. Health & Hygiene", "profile": "40°C / 800 RPM"},
    "New Clothes": {"category": "3. Health & Hygiene", "profile": "30°C / 800 RPM"},
    "Pets": {"category": "3. Health & Hygiene", "profile": "60°C / 1000 RPM"},
    "Masks Refresh": {"category": "3. Health & Hygiene", "profile": "40°C / 800 RPM"},
    "Masks Sanification": {"category": "3. Health & Hygiene", "profile": "60°C / 800 RPM"},
    "Bathrobe": {"category": "4. Home Care", "profile": "40°C / 800 RPM"},
    "Bed Linen": {"category": "4. Home Care", "profile": "60°C / 1000 RPM"},
    "Bed Linen Coloured": {"category": "4. Home Care", "profile": "40°C / 1000 RPM"},
    "Curtains": {"category": "4. Home Care", "profile": "30°C / 400 RPM"},
    "Curtains Coloured": {"category": "4. Home Care", "profile": "30°C / 400 RPM"},
    "Denim Jeans": {"category": "4. Home Care", "profile": "40°C / 800 RPM"},
    "Duvet & Quilts": {"category": "4. Home Care", "profile": "40°C / 800 RPM"},
    "Mats": {"category": "4. Home Care", "profile": "40°C / 800 RPM"},
    "Swimsuits & Bikinis": {"category": "4. Home Care", "profile": "30°C / 600 RPM"},
    "Tablecloths": {"category": "4. Home Care", "profile": "60°C / 1000 RPM"},
    "Tablecloths Coloured": {"category": "4. Home Care", "profile": "40°C / 1000 RPM"},
    "Delicate Tablecloths": {"category": "4. Home Care", "profile": "30°C / 800 RPM"},
    "Cashmere": {"category": "5. Special Care", "profile": "20°C / 400 RPM"},
    "Colored": {"category": "5. Special Care", "profile": "30°C / 800 RPM"},
    "Dark": {"category": "5. Special Care", "profile": "30°C / 800 RPM"},
    "Delicate Colored": {"category": "5. Special Care", "profile": "20°C / 800 RPM"},
    "Down Jackets": {"category": "5. Special Care", "profile": "30°C / 400 RPM"},
    "Lingerie": {"category": "5. Special Care", "profile": "30°C / 800 RPM"},
    "Silk (download)": {"category": "5. Special Care", "profile": "30°C / 800 RPM"},
    "Backpacks": {"category": "6. Sport & Leisure", "profile": "30°C / 400 RPM"},
    "Diving Suits": {"category": "6. Sport & Leisure", "profile": "30°C / 400 RPM"},
    "Gym Fit": {"category": "6. Sport & Leisure", "profile": "30°C / 1000 RPM"},
    "Ski Suit": {"category": "6. Sport & Leisure", "profile": "30°C / 400 RPM"},
    "Technical Fabrics": {"category": "6. Sport & Leisure", "profile": "30°C / 1000 RPM"},
    "Technical Jackets": {"category": "6. Sport & Leisure", "profile": "30°C / 400 RPM"},
    "Trainers": {"category": "6. Sport & Leisure", "profile": "20°C / 400 RPM"},
    "Bleaching": {"category": "7. Stains Proof", "profile": "0°C / 1000 RPM"},
    "Blood Stains": {"category": "7. Stains Proof", "profile": "60°C / 1000 RPM"},
    "Chocolate Stains": {"category": "7. Stains Proof", "profile": "60°C / 1000 RPM"},
    "Colored Anti-Stain": {"category": "7. Stains Proof", "profile": "40°C / 1000 RPM"},
    "Fruit Stains": {"category": "7. Stains Proof", "profile": "60°C / 1000 RPM"},
    "Perfect White": {"category": "7. Stains Proof", "profile": "60°C / 1000 RPM"},
    "Stain Remover": {"category": "7. Stains Proof", "profile": "60°C / 1000 RPM"},
    "Wine Stains": {"category": "7. Stains Proof", "profile": "60°C / 1000 RPM"},
    "Rapid Delicates 30 min": {"category": "8. Time & Energy Saver", "profile": "30°C / 800 RPM"},
    "Refresh 14 min": {"category": "8. Time & Energy Saver", "profile": "30°C / 800 RPM"},
    "Time Saver Cotton": {"category": "8. Time & Energy Saver", "profile": "40°C / 1200 RPM"},
    "Time Saver Mixed": {"category": "8. Time & Energy Saver", "profile": "40°C / 1000 RPM"},
    "Shirts": {"category": "9. Work", "profile": "30°C / 1000 RPM"},
    "Men's Trousers": {"category": "9. Work", "profile": "40°C / 800 RPM"},
}

TUMBLE_DRYER_PROGRAM_META_SQ: dict[str, dict[str, str]] = {
    "Whites": {"category": "1. Cycles", "profile": "Nxehtësi e Lartë"},
    "Eco": {"category": "1. Cycles", "profile": "Nxehtësi e Lartë"},
    "Whites Plus": {"category": "1. Cycles", "profile": "Nxehtësi e Lartë"},
    "Jeans": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Darks & Coloured": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Synthetics": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Shirts": {"category": "1. Cycles", "profile": "Nxehtësi e Ulët"},
    "Woolmark": {"category": "1. Cycles", "profile": "Nxehtësi e Ulët"},
    "Daily Perfect 59'": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Daily 45 min": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Saving 30 min": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Refresh": {"category": "1. Cycles", "profile": "Pa Nxehtësi"},
    "Relax Creases": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Sport Plus": {"category": "1. Cycles", "profile": "Nxehtësi Mesatare"},
    "Small Load": {"category": "1. Cycles", "profile": "Nxehtësi e Ulët"},
    "Baby": {"category": "2. Baby Care", "profile": "Nxehtësi e Lartë"},
    "Cuddly Toys": {"category": "2. Baby Care", "profile": "Nxehtësi e Ulët"},
    "Delicates Antiallergy": {"category": "3. Health & Hygiene", "profile": "Nxehtësi e Lartë"},
    "Air Refresh": {"category": "3. Health & Hygiene", "profile": "Pa Nxehtësi"},
    "Warm Embrace": {"category": "3. Health & Hygiene", "profile": "Pa Nxehtësi"},
    "Dehumidifier": {"category": "3. Health & Hygiene", "profile": "Pa Nxehtësi"},
    "Anti-Mites": {"category": "3. Health & Hygiene", "profile": "Nxehtësi e Lartë"},
    "Bathrobe": {"category": "4. Home Care", "profile": "Nxehtësi e Lartë"},
    "Bed Linen": {"category": "4. Home Care", "profile": "Nxehtësi e Lartë"},
    "Curtains": {"category": "4. Home Care", "profile": "Nxehtësi e Ulët"},
    "Denim Jeans": {"category": "4. Home Care", "profile": "Nxehtësi Mesatare"},
    "Duvet": {"category": "4. Home Care", "profile": "Nxehtësi e Lartë"},
    "Playsuits": {"category": "4. Home Care", "profile": "Nxehtësi e Ulët"},
    "Tablecloths": {"category": "4. Home Care", "profile": "Nxehtësi e Lartë"},
    "Delicate Tablecloths": {"category": "4. Home Care", "profile": "Nxehtësi e Ulët"},
    "Regenerates Waterproof": {"category": "5. Special Care", "profile": "Pa Nxehtësi"},
    "Easy Iron Cotton": {"category": "5. Special Care", "profile": "Nxehtësi Mesatare"},
    "Easy Iron Synthetics": {"category": "5. Special Care", "profile": "Nxehtësi Mesatare"},
    "Lingerie": {"category": "5. Special Care", "profile": "Nxehtësi e Ulët"},
    "Shirts Delicate": {"category": "5. Special Care", "profile": "Nxehtësi e Ulët"},
    "Swimsuits & Bikinis": {"category": "5. Special Care", "profile": "Nxehtësi e Ulët"},
    "Gym Fit": {"category": "6. Sport & Leisure", "profile": "Nxehtësi Mesatare"},
    "Technical Fabrics": {"category": "6. Sport & Leisure", "profile": "Nxehtësi Mesatare"},
    "Backpacks": {"category": "6. Sport & Leisure", "profile": "Nxehtësi e Ulët"},
    "Rapid 60 min Delicates": {"category": "7. Time & Energy Saver", "profile": "Nxehtësi Mesatare"},
}
